# Generated by Django 5.1.4 on 2025-04-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_categories_options_alter_chapters_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='info_4_search',
            field=models.CharField(default='', max_length=150, verbose_name='Отображаемая информация'),
        ),
    ]
