# Generated by Django 5.1.4 on 2025-04-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_goods_info_4_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='choice',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='', max_length=50),
        ),
    ]
