# Generated by Django 5.1.4 on 2025-04-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_goods_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='choice',
            field=models.CharField(choices=[('Нет', 'Нет'), ('Да', 'Да')], default='Нет', max_length=50, verbose_name='Новые товары'),
        ),
    ]
