# Generated by Django 5.1.4 on 2025-06-09 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_categories_image_alter_goods_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='vategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.categories', verbose_name='Категория'),
        ),
    ]
