# Generated by Django 5.1.4 on 2025-06-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_alter_goods_vategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='vategory',
            new_name='category',
        ),
    ]
