# Generated by Django 5.1.4 on 2025-06-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_rename_vategory_goods_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='l_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество размера L'),
        ),
        migrations.AddField(
            model_name='goods',
            name='m_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество размера M'),
        ),
        migrations.AddField(
            model_name='goods',
            name='s_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество размера S'),
        ),
        migrations.AddField(
            model_name='goods',
            name='xl_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество размера XL'),
        ),
        migrations.AddField(
            model_name='goods',
            name='xs_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество размера XS'),
        ),
    ]
