# Generated by Django 5.1.4 on 2025-06-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_goods_l_count_goods_m_count_goods_s_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='quantity',
        ),
    ]
