# Generated by Django 5.1.4 on 2025-01-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Сlothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_gender', models.CharField(max_length=100)),
                ('clothing_category', models.CharField(max_length=100)),
                ('name_of_cloth', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('clothing_color', models.CharField(max_length=100)),
                ('clothing_size', models.CharField(max_length=100)),
                ('clothing_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('clothing_count', models.IntegerField(default=0)),
                ('clothing_image', models.ImageField(upload_to='media/')),
                ('clothing_description', models.TextField()),
                ('clothing_article', models.IntegerField()),
                ('new_collection', models.BooleanField()),
            ],
        ),
    ]
